title: Hello, world! I'm eric laurits
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: eric laurits # add your name
author-img: profile.png # add your photo
about-author: Teacher, teacher educator, and recovering photographer currently in foreign service in Kenya. # add description
social-twitter: ericlaurits # add your Twitter handle
social-facebook: # add your Facebook handle
social-instagram: ericlaurits # add your Email address
social-github: artemsheludko # add your Github handle
social-linkedin: ericlaurits # add your Linkedin handle
social-email: eric@ericlaurits.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
